### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by larshp** [LinkeIT/AWS_S3_SDK_for_ABAP#3]
Hi Jordi,
Have you considered putting the source code in the git repository? So it is possible to read the code and see which objects are part of the project.

The project looks very interesting, however I typically recommend customers against importing transports from vendors that they do not know.

The following tools might help:
https://app.assembla.com/spaces/saplink/wiki
https://github.com/larshp/abapGit (it also includes a uninstall feature so ZUNINSTALL_S3_FOR_SAP is not needed)

just an idea

**Comment by JordiEscodaLinkeIT** [comment]
Hi Lars,
Yes, of course, we could put the source code. But consider that I did not develop in customer namespace, it is developed in reserved namespace /RS3/. So I'm afraid anyone will be able to install it by using SAPLink. For this reason I think is useless. What do you think?

And refactoring to customer namespace could lead to some collision. It is not a single report. There are 46 dictionary objects, 18 classes, 8 programs, 1 message class. 

Ideas are welcome!

**Comment by larshp** [comment]
hmm, the project is licensed as GPL, so if I install the transport and want to contribute some changes to the code, will I be able to edit the source code in the SAP system?

As far as I remember, then a key is required to be able to edit objects in a customer/partner namespace?

**Comment by larshp** [comment]
Also see https://github.com/larshp/abapGit/issues/369 where we recently had some discussions on this topic. 

From my point of view it is easiest just to rename to something like ZCL_RS3_foo, but on the other hand namespaces are the correct solution to name collision.

**Comment by JordiEscodaLinkeIT** [comment]
Yes Lars, 
You are right, it is licensed as GPL. This means the source code should be modifiable. 
It is our aim to encourage using S3 for SAP and contribute. 
The code can be seen if you install it through the Transport request. 
Using reserved namespace ensures no collisions. But the drawback is that is needed a key to modify the code. 
I hope SAP will consider thinking abut safe Open Source projects and in a near future will give a solution for this. 
In the meantime we are open to receive any request and implement it in case it is aligned with the project.

**Comment by larshp** [comment]
:+1:
